# ===================================================================
# Standard Spring Boot properties
# ===================================================================
project:
  version: @project.version@

server:
  port: 8080
  tomcat:
    accesslog:
      directory: /var/log/minid-notification-server/
      enabled: true
      rotate: false
      pattern: "%h\u0009%l\u0009%u\u0009%t\u0009\u0022%r\u0022\u0009%s\u0009%b\u0009%D\u0009%{no.difi.correlationId}i"
    remoteip:
      remote-ip-header: X-Forwarded-For
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
    encoding:
      force: true
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Spring boot actuator endpoint
management:
  endpoint:
    flyway:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "version, info, flyway"
      #        include: "health, info, version"
    jmx:
      exposure:
        exclude: "*"
#  endpoint:
#    health:
#      show-details: always
#      enabled: true
  info:
    git:
      mode: full
#  health:
#    mail:
#      enabled: false
#    diskspace:
#      enabled: false
#    metrics:
#      enabled: false


spring:
  jpa:
    open-in-view: false
  mvc:
    throw-exception-if-no-handler-found: true

  # Spring Security - OAuth 2 provider
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://eid-systest-web01.dmz.local/idporten-oidc-provider/
        opaque-token:
          introspection-uri: https://eid-systest-web01.dmz.local/idporten-oidc-provider/tokeninfo
          client-id: test_rp_systest
          client-secret: password

  datasource:
    url: jdbc:mysql://eid-systest-db01.dmz.local:3306/minid_notification?useMysqlMetadata=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: minid_notif
    password: password

  flyway:
    validate-on-migrate: true
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://eid-systest-db01.dmz.local:3306/minid_notification?useMysqlMetadata=true
    user: minid_notif
    password: password

# ===================================================================
# Application specific properties
# ===================================================================
digdir:
  firebase:
    credentials-json: classpath:firebase-credentials.json
